Repository elastic/elasticsearch-java, pull requests merged in 2021-12, with the labels that each got.

#49 Fix the link to the full documentation
  README.md
Labels: documentation, 8.0, 7.16.0

#52 [docs] Update with the latest changes and use compilable examples
  docs/api-conventions.asciidoc
  docs/connecting.asciidoc
  docs/index-local.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
  docs/local/README.md
  docs/local/elasticsearch/docs/java-rest/low-level/index.asciidoc
  docs/migrate.asciidoc
  java-client/src/test/java/co/elastic/clients/documentation/ApiConventionsTest.java
Labels: documentation, 8.0, 7.16.0

#59 Fix race condition in LazyDeserializer initialization
  java-client/src/main/java/co/elastic/clients/json/LazyDeserializer.java
  java-client/src/test/java/co/elastic/clients/json/LazyDeserializerTest.java
Labels: backport 7.16, backport 8.0

#63 Change the JSON-P implementation from Glassfish to Parsson
  java-client/build.gradle.kts
Labels: backport 7.16, backport 8.0

#68 Accept null values in arrays
  java-client/src/main/java/co/elastic/clients/json/JsonpDeserializerBase.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/BuiltinTypesTest.java
Labels: backport 7.16, backport 8.0, backport 7.17

#73 Add links to javadoc and source code
  docs/index-local.asciidoc
  docs/index.asciidoc
  docs/javadoc-and-source.asciidoc
Labels: documentation, backport 7.16, backport 8.0, backport 7.17
