Repository elastic/elasticsearch-java, pull requests merged in 2021-09, with the labels that each got.

#14 [DOCS] Fixes typo
  docs/installation.asciidoc
Labels: documentation, 8.0, 7.x

#17 [DOCS] Adds intro text to the index file, changes snippet attributes
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
Labels: documentation, 8.0, 7.x, 7.15

#19 [7.x][DOCS] Adds intro text to the index file, changes snippet attributes
  docs/connecting.asciidoc
  docs/index.asciidoc
  docs/installation.asciidoc
Labels: documentation, 7.x

#22 [DOCS] Removes partintro from book index
  docs/index.asciidoc
Labels: documentation, 8.0, 7.x

#23 [7.x][DOCS] Removes partintro from book index
  docs/index.asciidoc
Labels: documentation, 7.x

#24 [DOCS] Removes content from index and changes book title
  docs/index.asciidoc
  docs/introduction.asciidoc
Labels: documentation, 8.0, 7.x

#25 Update Maven coordinates
  docs/installation.asciidoc
Labels: documentation, 8.0, 7.x
