Repository elastic/elasticsearch-java, pull requests merged in 2021-10, with the labels that each got.

#27 Promote client stability in docs
  docs/connecting.asciidoc
  docs/installation.asciidoc
  docs/introduction.asciidoc
Labels: documentation, 7.x, 7.15

#21 [DOCS] Adds low-level subsection from ES repo to TOC
  docs/index.asciidoc
Labels: documentation, 8.0, 7.x

#28 [7.x][DOCS] Adds low-level subsection from ES repo to TOC
  docs/index.asciidoc
Labels: documentation, 7.x

#29 [DOCS] Updates the link in Introduction that points to LLRC
  docs/introduction.asciidoc
Labels: documentation, 8.0, 7.x

#30 [7.x][DOCS] Updates the link in Introduction that points to LLRC.
  docs/introduction.asciidoc
Labels: documentation, 7.x
