Repository elastic/elasticsearch-java, pull requests merged in 2022-06, with the labels that each got.

#301 Add docs about MissingRequiredPropertyException
  docs/api-conventions/exceptions.asciidoc
  docs/api-conventions/index.asciidoc
  docs/index.asciidoc
  docs/troubleshooting/index.asciidoc
  docs/troubleshooting/missing-required-property.asciidoc
  docs/usage/aggregations.asciidoc
Labels: >documentation, backport 7.17, backport 8.2, backport 8.3

#284 Actualize libs versions. Move tests to junit jupiter
  docs/getting-started/migrate-hlrc.asciidoc
  java-client/build.gradle.kts
  java-client/src/test/java/co/elastic/clients/documentation/api_conventions/ApiConventionsTest.java
  java-client/src/test/java/co/elastic/clients/documentation/api_conventions/LoadingJsonTest.java
  java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
  java-client/src/test/java/co/elastic/clients/documentation/getting_started/MigrateHlrcTest.java
  java-client/src/test/java/co/elastic/clients/documentation/usage/AggregationsTest.java
  java-client/src/test/java/co/elastic/clients/documentation/usage/IndexingBulkTest.java
  java-client/src/test/java/co/elastic/clients/documentation/usage/IndexingTest.java
  java-client/src/test/java/co/elastic/clients/documentation/usage/ReadingTest.java
  java-client/src/test/java/co/elastic/clients/documentation/usage/SearchingTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/ClientTests.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/ParsingTests.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/api/query2/QueryTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/containers/SomeUnionTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/experiments/inheritance/InheritanceTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonDataTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpMapperTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/JsonpUtilsTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JacksonJsonpParserTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JacksonMapperTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/json/jackson/JsonValueParserTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/BehaviorsTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/BuiltinTypesTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/ClassStructureTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/EndpointTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/EnumTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/ModelTestCase.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/RequestEncodingTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/SerializationTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/TypedKeysTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/UnionTests.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/VariantsTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/spec_issues/SpecIssuesTest.java
  java-client/src/test/java/co/elastic/clients/json/JsonpMappingExceptionTest.java
  java-client/src/test/java/co/elastic/clients/json/LazyDeserializerTest.java
  java-client/src/test/java/co/elastic/clients/json/WithJsonTest.java
  java-client/src/test/java/co/elastic/clients/transport/RequestOptionsTest.java
  java-client/src/test/java/co/elastic/clients/util/DateTimeTest.java
Labels: >enhancement, backport 7.17, backport 8.3

#316 Allow serializing aggregations without typed keys
  docs/troubleshooting/index.asciidoc
  docs/troubleshooting/serialize-without-typed-keys.asciidoc
  java-client/src/main/java/co/elastic/clients/json/ExternallyTaggedUnion.java
  java-client/src/main/java/co/elastic/clients/json/JsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
  java-client/src/main/java/co/elastic/clients/json/JsonpMapperFeatures.java
  java-client/src/main/java/co/elastic/clients/json/SimpleJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/util/WithJsonObjectBuilderBase.java
  java-client/src/test/java/co/elastic/clients/documentation/troubleshooting/TroubleShootingTests.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/TypedKeysTest.java
Labels: >enhancement, backport 7.17, backport 8.3

#327 Fix booleans in JacksonJsonpGenerator and add tests
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
  java-client/src/test/java/co/elastic/clients/json/jackson/JacksonJsonpGeneratorTest.java
Labels: >bug, backport 7.17, backport 8.3
