Repository elastic/elasticsearch-java, pull requests merged in 2023-09, with the labels that each got.

#664 [8.10] Add documentation for the OpenTelemetry instrumentation (#658)
  docs/images/otel-waterfall-instrumented-without-http.jpg
  docs/images/otel-waterfall-instrumented.jpg
  docs/images/otel-waterfall-retries.jpg
  docs/setup/index.asciidoc
  docs/setup/open-telemetry.asciidoc
  java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
Labels: >documentation

#668 [DOCS] Fix `welcome-to-elastic` link
  docs/index-custom-title-page.html
Labels: >documentation, backport 8.7, backport 8.8, backport 8.9, backport 8.10

#669 [8.10] [DOCS] Fix `welcome-to-elastic` link (#668)
  docs/index-custom-title-page.html
Labels: backport

#670 [8.9] [DOCS] Fix `welcome-to-elastic` link (#668)
  docs/index-custom-title-page.html
Labels: backport

#671 [8.8] [DOCS] Fix `welcome-to-elastic` link (#668)
  docs/index-custom-title-page.html
Labels: backport

#672 [8.7] [DOCS] Fix `welcome-to-elastic` link (#668)
  docs/index-custom-title-page.html
Labels: backport
