Repository elastic/elasticsearch-java, pull requests merged in 2023-06, with the labels that each got.

#597 Fix spurious JSON event emitted by JsonpUtils.copy()
  java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
  java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
Labels: >bug, backport 8.8

#600 Throttling info in DeleteByQueryResponse is optional
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/DeleteByQueryResponse.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/doc-files/api-spec.html
Labels: >api-spec

#605 [DOCS] Adds getting started MDX to the serverless client docs
  java-client-serverless/docs/getting-started.mdx
  java-client-serverless/docs/images/copy-endpoint.gif
  java-client-serverless/docs/images/setup-api-key.gif
  java-client-serverless/index.mdx
Labels: >documentation
