Repository elastic/elasticsearch-java, pull requests merged in 2024-03, with the labels that each got.

#760 Add misc improvements to the framework
  java-client-serverless/src/main/java/co/elastic/clients/elasticsearch/_types/ElasticsearchException.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/ElasticsearchException.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/FieldValue.java
  java-client/src/main/java/co/elastic/clients/json/BufferingJsonGenerator.java
  java-client/src/main/java/co/elastic/clients/json/BufferingJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/DelegatingJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
  java-client/src/main/java/co/elastic/clients/json/JsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/JsonpMapperBase.java
  java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpGenerator.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/transport/ElasticsearchTransportBase.java
  java-client/src/main/java/co/elastic/clients/transport/Endpoint.java
  java-client/src/main/java/co/elastic/clients/transport/endpoints/BinaryDataResponse.java
  java-client/src/main/java/co/elastic/clients/util/ByteArrayBinaryData.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestServer.java
  java-client/src/test/java/co/elastic/clients/json/jackson/JacksonMapperTest.java
  java-client/src/test/java/co/elastic/clients/testkit/MockHttpClient.java
Labels: >enhancement, backport 7.17, backport 8.13

#764 ObjectsEsqlAdapter refactor
  java-client/src/main-flavored/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlAdapter.java
  java-client/src/main-flavored/java/co/elastic/clients/elasticsearch/_helpers/esql/objects/ObjectsEsqlAdapter.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlAdapterEndToEndTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/esql/EsqlAdapterTest.java
Labels: backport 8.13

#768 Update Jackson version
  docs/getting-started.asciidoc
  docs/setup/installation.asciidoc
  example-transports/build.gradle.kts
  java-client-serverless/build.gradle.kts
  java-client-serverless/docs/getting-started.mdx
  java-client/build.gradle.kts
Labels: backport 7.17, backport 8.13
