Repository elastic/elasticsearch-java, pull requests merged in 2024-08, with the labels that each got.

#851 Make ApiClient and subclasses Closeable
  docs/api-conventions/object-lifecycles.asciidoc
  docs/release-notes/release-highlights.asciidoc
  java-client/src/main/java/co/elastic/clients/ApiClient.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
  java-client/src/test/java/co/elastic/clients/documentation/getting_started/ConnectingTest.java
Labels: Category: Enhancement

#853 Refine BooleanEndpoint so that 4xx status codes other than 404 are considered as errors
  java-client/src/main/java/co/elastic/clients/transport/endpoints/BooleanEndpoint.java
Labels: Category: Bug, backport 8.15

#858 Add support for shortcut properties of non-primitive type
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/FunctionScoreQuery.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/FuzzyQuery.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/MatchQuery.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_types/query_dsl/TermQuery.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/rank_eval/RankEvalQuery.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/CompletionContext.java
  java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
  java-client/src/main/java/co/elastic/clients/json/ObjectDeserializer.java
  java-client/src/main/java/co/elastic/clients/json/UnionDeserializer.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpParser.java
  java-client/src/main/java/co/elastic/clients/util/WithJsonObjectBuilderBase.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/BehaviorsTest.java
  java-client/src/test/java/co/elastic/clients/json/jackson/JsonValueParserTest.java
Labels: Category: Bug, backport 7.17, backport 8.15

#870 Addressing bulk ingester stuck threads
  java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java
Labels: backport 7.17, backport 8.15
