Repository elastic/elasticsearch-java, pull requests merged in 2025-05, with the labels that each got.

#1005 [Docs] Add mapping for deleted file
  docs/reference/index.md
Labels: Area: Documentation, backport 9.0

#1006 Fully targeting java 8
  java-client/build.gradle.kts
Labels: backport 8.17, backport 8.x

#1008 Make sure to always target java 17
  java-client/build.gradle.kts
Labels: backport 9.0

#1010 Fix dependencies + pom building
  java-client/build.gradle.kts
Labels: backport 9.0

#1011 Using fixed minor version of rest-client - 8
  java-client/build.gradle.kts
Labels: backport 8.18, backport 8.17

#1014 [Docs] Fix broken Javadoc link
  docs/reference/javadoc-source-code.md
Labels: Area: Documentation, backport 9.0

#1015 [docs] Add `products` to `docset.yml`
  docs/docset.yml
Labels: Area: Documentation
