Repository elastic/elasticsearch-java, pull requests merged in 2025-03, with the labels that each got.

#956 [docs] Fix external links
  docs/reference/_basic_authentication.md
  docs/reference/_encrypted_communication.md
  docs/reference/_timeouts.md
  docs/reference/java-rest-low-usage-initialization.md
  docs/reference/java-rest-low-usage-logging.md
  docs/reference/java-rest-low-usage-responses.md
  docs/reference/java-rest-low-usage-shading.md
Labels: Area: Documentation

#961 Maven central release with nexus plugin
  .ci/configure_signing.sh
  .ci/make.sh
  build.gradle.kts
  java-client/build.gradle.kts
  settings.gradle.kts
Labels: backport 7.17, backport 8.16, backport 9.0, backport 8.18, backport 8.17

#966 Updates navigation titles and descriptions for release notes
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
Labels: Area: Documentation

#871 General build update + unit test action
  .ci/Dockerfile
  .github/workflows/unit-tests.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  java-client/build.gradle.kts
Labels: backport 9.0

#972 [docs] Remove reliance on temporary redirects
  docs/reference/aggregations.md
Labels: Area: Documentation
