Repository elastic/elasticsearch-java, pull requests merged in 2025-08, with the labels that each got.

#1048 [DOCS] Adds CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: Area: Documentation

#1049 Safe response consumer for rest5client
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/Rest5ClientOptions.java
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/SafeResponseConsumer.java
  java-client/src/test/java/co/elastic/clients/transport/rest5_client/low_level/SafeResponseConsumerTest.java
Labels: backport 9.0, backport 9.1

#1055 Rest5Client consumer limit check fix
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/BufferedByteConsumer.java
Labels: Area: Transport, backport 9.0, backport 9.1

#1047 [DOCS] Rest 5 client fixes
  docs/reference/transport/rest5-client/config/basic_authentication.md
  docs/reference/transport/rest5-client/config/timeouts.md
Labels: Area: Documentation, backport, backport 9.0, backport 9.1

#1059 Update logging.md
  docs/reference/transport/rest5-client/usage/logging.md
Labels: backport 9.0, backport 9.1

#1060 Http2 bug workaround
  java-client/src/main/java/co/elastic/clients/transport/ElasticsearchTransportBase.java
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/Rest5ClientOptions.java
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/BufferedByteConsumer.java
Labels: backport 9.0, backport 9.1

#1044 Publish javadoc with publish to s3 service pipeline
  .buildkite/release_central.yml
  .ci/make.sh
  docs/reference/javadoc-source-code.md
Labels: backport 8.19, backport 9.0, backport 8.18, backport 8.17, backport 9.1
