Repository elastic/elasticsearch-java, pull requests merged in 2025-04, with the labels that each got.

#973 [Docs] Remove stale serverless page
  docs/reference/getting-started-serverless.md
  docs/reference/toc.yml
Labels: Area: Documentation, backport 9.0

#971 Avoid executing stress test from gha
  .github/workflows/unit-tests.yml
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterRetryPolicyTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java
Labels: backport 9.0

#978 [docs] Add missing mapped pages
  docs/release-notes/index.md
Labels: Area: Documentation

#976 Use Jackson as the default JSON implementations, update libraries
  docs/reference/getting-started.md
  docs/reference/installation.md
  java-client/build.gradle.kts
  java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
  java-client/src/main/java/co/elastic/clients/json/SimpleJsonpMapper.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonProvider.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JsonValueParser.java
  java-client/src/main/java/co/elastic/clients/json/jsonb/JsonbJsonpMapper.java
  java-client/src/test/java/co/elastic/clients/json/JsonpUtilsTest.java
  java-client/src/test/java/co/elastic/clients/testkit/ModelTestCase.java
Labels: Area: Transport, backport 9.0

#979 Handle path prefixes when creating clients using URIs
  java-client/src/main/java/co/elastic/clients/transport/rest5_client/low_level/Rest5Client.java
  java-client/src/main/java/co/elastic/clients/transport/rest_client/RestClientTransport.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/ElasticsearchTestClient.java
  java-client/src/test/java/co/elastic/clients/transport/ElasticsearchTransportConfigTest.java
Labels: Category: Bug, backport 9.0

#982 Support include_names_queries_score
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/MsearchRequest.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/SearchRequest.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/core/search/Hit.java
  java-client/src/main/java/co/elastic/clients/json/JsonpDeserializer.java
  java-client/src/main/java/co/elastic/clients/json/JsonpDeserializerBase.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/BehaviorsTest.java
Labels: backport 9.0

#992 9.0.0 docs
  docs/reference/release-highlights.md
  docs/release-notes/9-0-0.md
  docs/release-notes/breaking-changes.md
  docs/release-notes/deprecations.md
  docs/release-notes/index.md
  docs/release-notes/known-issues.md
  docs/release-notes/toc.yml
Labels: backport 9.0

#1000 [docs] Fix image paths for docs-assembler
  docs/reference/getting-started.md
  docs/reference/setup/opentelemetry.md
Labels: Area: Documentation, backport, backport 9.0

#1001 [docs] Fix various syntax and rendering errors
  docs/reference/transport/rest-client/sniffer/maven_repository.md
  docs/reference/transport/rest-client/usage/maven.md
  docs/reference/transport/rest-client/usage/requests.md
Labels: Area: Documentation
