Repository elastic/elasticsearch-java, pull requests merged in 2025-02, with the labels that each got.

#934 Add release CI pipeline
  .buildkite/configure_signing.sh
  .buildkite/pipeline.yml
  .buildkite/release_central.yaml
  .ci/Dockerfile
  .ci/configure_signing.sh
  .ci/make.sh
  .ci/release_central.sh
  .ci/release_dra.sh
  .github/workflows/release_central.yml
  build.gradle.kts
  catalog-info.yaml
  java-client/build.gradle.kts
Labels: Area: CI

#936 Making variant tag more lenient
  java-client/src/main/java/co/elastic/clients/json/JsonpUtils.java
  java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpParser.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/model/VariantsTest.java
Labels: backport 8.x, backport 9.0, backport 8.18

#942 Run tests in non-strict JSON mode, like real applications
  java-client/src/test/java/co/elastic/clients/json/JsonpMappingExceptionTest.java
  java-client/src/test/java/co/elastic/clients/testkit/ModelTestCase.java
Labels: Category: Enhancement, Area: Transport, backport 8.x, backport 9.0

#930 Bulk ingester retry policy
  java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngester.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/IngesterOperation.java
  java-client/src/main/java/co/elastic/clients/elasticsearch/_helpers/bulk/RetryableBulkOperation.java
  java-client/src/main/java/co/elastic/clients/transport/BackoffPolicy.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterRetryPolicyTest.java
  java-client/src/test/java/co/elastic/clients/elasticsearch/_helpers/bulk/BulkIngesterTest.java
Labels: backport 8.x, backport 9.0

#951 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: Area: Documentation

#953 [docs] Clean up cross-repo links
  docs/reference/aggregations.md
  docs/reference/building-objects.md
  docs/reference/package-structure.md
  docs/reference/using-java-api-client.md
Labels: Area: Documentation
